# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget openenclave::oe_includes openenclave::oehost openenclave::oesign openenclave::oeutil openenclave::oecore openenclave::oecore-lvi-cfg openenclave::oedebugmalloc openenclave::oedebugmalloc-lvi-cfg openenclave::oecryptombedtls openenclave::oecryptombedtls-lvi-cfg openenclave::oecryptoopenssl openenclave::oecryptoopenssl-lvi-cfg openenclave::oeseal_gcmaes openenclave::oeseal_gcmaes-lvi-cfg openenclave::oeenclave openenclave::oeenclave-lvi-cfg openenclave::oedlmalloc_obj openenclave::oedlmalloc_obj-lvi-cfg openenclave::libcxx openenclave::libcxx-lvi-cfg openenclave::libcxxrt openenclave::libcxxrt-lvi-cfg openenclave::libunwind openenclave::libunwind-lvi-cfg openenclave::oelibc_includes openenclave::mbedcrypto_static openenclave::mbedcrypto_static-lvi-cfg openenclave::mbedx509 openenclave::mbedx509-lvi-cfg openenclave::mbedtls openenclave::mbedtls-lvi-cfg openenclave::mbedcrypto openenclave::mbedcrypto-lvi-cfg openenclave::oesnmalloc_obj openenclave::oesnmalloc_obj-lvi-cfg openenclave::oesnmalloc openenclave::oesnmalloc-lvi-cfg openenclave::opensslcrypto openenclave::opensslcrypto-lvi-cfg openenclave::opensslssl openenclave::opensslssl-lvi-cfg openenclave::openssl openenclave::openssl-lvi-cfg openenclave::oelibc openenclave::oelibc-lvi-cfg openenclave::oelibasm openenclave::oelibasm-lvi-cfg openenclave::oelibcxx openenclave::oelibcxx-lvi-cfg openenclave::oesyscall openenclave::oesyscall-lvi-cfg openenclave::oehostfs openenclave::oehostfs-lvi-cfg openenclave::oehostresolver openenclave::oehostresolver-lvi-cfg openenclave::oehostsock openenclave::oehostsock-lvi-cfg openenclave::oehostepoll openenclave::oehostepoll-lvi-cfg openenclave::oedebugrt)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target openenclave::oe_includes
add_library(openenclave::oe_includes INTERFACE IMPORTED)

set_target_properties(openenclave::oe_includes PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target openenclave::oehost
add_library(openenclave::oehost STATIC IMPORTED)

set_target_properties(openenclave::oehost PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<NOT:\$<CONFIG:debug>>:_FORTIFY_SOURCE=2>"
  INTERFACE_COMPILE_OPTIONS "-fstack-protector-strong"
  INTERFACE_LINK_LIBRARIES "openenclave::oe_includes;\$<LINK_ONLY:openenclave::oedebugrt>;\$<LINK_ONLY:openenclave::crypto>;\$<LINK_ONLY:openenclave::dl>;\$<LINK_ONLY:Threads::Threads>;-Wl,-z,noexecstack"
)

# Create imported target openenclave::oesign
add_executable(openenclave::oesign IMPORTED)

# Create imported target openenclave::oeutil
add_executable(openenclave::oeutil IMPORTED)

# Create imported target openenclave::oecore
add_library(openenclave::oecore STATIC IMPORTED)

set_target_properties(openenclave::oecore PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "OE_BUILD_ENCLAVE"
  INTERFACE_COMPILE_OPTIONS "-m64;-fPIE;-nostdinc;-fstack-protector-strong;-fvisibility=hidden;-fno-omit-frame-pointer;-ffunction-sections;-fdata-sections;-ftls-model=local-exec;\$<\$<COMPILE_LANGUAGE:CXX>:-nostdinc++>"
  INTERFACE_LINK_LIBRARIES "openenclave::oe_includes;openenclave::oe_includes;openenclave::oedlmalloc_obj;-nostdlib;-nodefaultlibs;-nostartfiles;-Wl,--no-undefined,-Bstatic,-Bsymbolic,--export-dynamic,-pie,--build-id;-Wl,-z,noexecstack;-Wl,-z,now;-Wl,-gc-sections"
)

# Create imported target openenclave::oecore-lvi-cfg
add_library(openenclave::oecore-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oecore-lvi-cfg PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "OE_BUILD_ENCLAVE"
  INTERFACE_COMPILE_OPTIONS "-m64;-fPIE;-nostdinc;-fstack-protector-strong;-fvisibility=hidden;-fno-omit-frame-pointer;-ffunction-sections;-fdata-sections;-ftls-model=local-exec;\$<\$<COMPILE_LANGUAGE:CXX>:-nostdinc++>"
  INTERFACE_LINK_LIBRARIES "openenclave::oe_includes;openenclave::oe_includes;openenclave::oedlmalloc_obj-lvi-cfg;-nostdlib;-nodefaultlibs;-nostartfiles;-Wl,--no-undefined,-Bstatic,-Bsymbolic,--export-dynamic,-pie,--build-id;-Wl,-z,noexecstack;-Wl,-z,now;-Wl,-gc-sections"
)

# Create imported target openenclave::oedebugmalloc
add_library(openenclave::oedebugmalloc STATIC IMPORTED)

set_target_properties(openenclave::oedebugmalloc PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "OE_USE_DEBUG_MALLOC"
  INTERFACE_LINK_LIBRARIES "openenclave::oecore"
)

# Create imported target openenclave::oedebugmalloc-lvi-cfg
add_library(openenclave::oedebugmalloc-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oedebugmalloc-lvi-cfg PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "OE_USE_DEBUG_MALLOC"
  INTERFACE_LINK_LIBRARIES "openenclave::oecore-lvi-cfg"
)

# Create imported target openenclave::oecryptombedtls
add_library(openenclave::oecryptombedtls STATIC IMPORTED)

set_target_properties(openenclave::oecryptombedtls PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedcrypto"
)

# Create imported target openenclave::oecryptombedtls-lvi-cfg
add_library(openenclave::oecryptombedtls-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oecryptombedtls-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedcrypto-lvi-cfg"
)

# Create imported target openenclave::oecryptoopenssl
add_library(openenclave::oecryptoopenssl STATIC IMPORTED)

set_target_properties(openenclave::oecryptoopenssl PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::openssl"
)

# Create imported target openenclave::oecryptoopenssl-lvi-cfg
add_library(openenclave::oecryptoopenssl-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oecryptoopenssl-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::openssl-lvi-cfg"
)

# Create imported target openenclave::oeseal_gcmaes
add_library(openenclave::oeseal_gcmaes OBJECT IMPORTED)

# Create imported target openenclave::oeseal_gcmaes-lvi-cfg
add_library(openenclave::oeseal_gcmaes-lvi-cfg OBJECT IMPORTED)

# Create imported target openenclave::oeenclave
add_library(openenclave::oeenclave STATIC IMPORTED)

set_target_properties(openenclave::oeenclave PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc"
)

# Create imported target openenclave::oeenclave-lvi-cfg
add_library(openenclave::oeenclave-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oeenclave-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc-lvi-cfg"
)

# Create imported target openenclave::oedlmalloc_obj
add_library(openenclave::oedlmalloc_obj INTERFACE IMPORTED)

# Create imported target openenclave::oedlmalloc_obj-lvi-cfg
add_library(openenclave::oedlmalloc_obj-lvi-cfg INTERFACE IMPORTED)

# Create imported target openenclave::libcxx
add_library(openenclave::libcxx INTERFACE IMPORTED)

set_target_properties(openenclave::libcxx PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc"
)

# Create imported target openenclave::libcxx-lvi-cfg
add_library(openenclave::libcxx-lvi-cfg INTERFACE IMPORTED)

set_target_properties(openenclave::libcxx-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc-lvi-cfg"
)

# Create imported target openenclave::libcxxrt
add_library(openenclave::libcxxrt INTERFACE IMPORTED)

set_target_properties(openenclave::libcxxrt PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc"
)

# Create imported target openenclave::libcxxrt-lvi-cfg
add_library(openenclave::libcxxrt-lvi-cfg INTERFACE IMPORTED)

set_target_properties(openenclave::libcxxrt-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc-lvi-cfg"
)

# Create imported target openenclave::libunwind
add_library(openenclave::libunwind INTERFACE IMPORTED)

set_target_properties(openenclave::libunwind PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc"
)

# Create imported target openenclave::libunwind-lvi-cfg
add_library(openenclave::libunwind-lvi-cfg INTERFACE IMPORTED)

set_target_properties(openenclave::libunwind-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc-lvi-cfg"
)

# Create imported target openenclave::oelibc_includes
add_library(openenclave::oelibc_includes INTERFACE IMPORTED)

set_target_properties(openenclave::oelibc_includes PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "\$<\$<COMPILE_LANGUAGE:CXX>:${_IMPORT_PREFIX}/include/openenclave/3rdparty/libcxx>;${_IMPORT_PREFIX}/include/openenclave/3rdparty/libc"
)

# Create imported target openenclave::mbedcrypto_static
add_library(openenclave::mbedcrypto_static STATIC IMPORTED)

set_target_properties(openenclave::mbedcrypto_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/openenclave/3rdparty"
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc;openenclave::oe_includes"
)

# Create imported target openenclave::mbedcrypto_static-lvi-cfg
add_library(openenclave::mbedcrypto_static-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::mbedcrypto_static-lvi-cfg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/openenclave/3rdparty"
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc-lvi-cfg;openenclave::oe_includes"
)

# Create imported target openenclave::mbedx509
add_library(openenclave::mbedx509 STATIC IMPORTED)

set_target_properties(openenclave::mbedx509 PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedcrypto_static"
)

# Create imported target openenclave::mbedx509-lvi-cfg
add_library(openenclave::mbedx509-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::mbedx509-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedcrypto_static-lvi-cfg"
)

# Create imported target openenclave::mbedtls
add_library(openenclave::mbedtls STATIC IMPORTED)

set_target_properties(openenclave::mbedtls PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedx509"
)

# Create imported target openenclave::mbedtls-lvi-cfg
add_library(openenclave::mbedtls-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::mbedtls-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedx509-lvi-cfg"
)

# Create imported target openenclave::mbedcrypto
add_library(openenclave::mbedcrypto INTERFACE IMPORTED)

set_target_properties(openenclave::mbedcrypto PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedtls"
)

# Create imported target openenclave::mbedcrypto-lvi-cfg
add_library(openenclave::mbedcrypto-lvi-cfg INTERFACE IMPORTED)

set_target_properties(openenclave::mbedcrypto-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedtls-lvi-cfg"
)

# Create imported target openenclave::oesnmalloc_obj
add_library(openenclave::oesnmalloc_obj INTERFACE IMPORTED)

# Create imported target openenclave::oesnmalloc_obj-lvi-cfg
add_library(openenclave::oesnmalloc_obj-lvi-cfg INTERFACE IMPORTED)

# Create imported target openenclave::oesnmalloc
add_library(openenclave::oesnmalloc STATIC IMPORTED)

set_target_properties(openenclave::oesnmalloc PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oesnmalloc_obj"
)

# Create imported target openenclave::oesnmalloc-lvi-cfg
add_library(openenclave::oesnmalloc-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oesnmalloc-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oesnmalloc_obj-lvi-cfg"
)

# Create imported target openenclave::opensslcrypto
add_library(openenclave::opensslcrypto STATIC IMPORTED)

set_target_properties(openenclave::opensslcrypto PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/openenclave/3rdparty"
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc;openenclave::oe_includes"
)

# Create imported target openenclave::opensslcrypto-lvi-cfg
add_library(openenclave::opensslcrypto-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::opensslcrypto-lvi-cfg PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/openenclave/3rdparty"
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc-lvi-cfg;openenclave::oe_includes"
)

# Create imported target openenclave::opensslssl
add_library(openenclave::opensslssl STATIC IMPORTED)

set_target_properties(openenclave::opensslssl PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::opensslcrypto"
)

# Create imported target openenclave::opensslssl-lvi-cfg
add_library(openenclave::opensslssl-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::opensslssl-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::opensslcrypto-lvi-cfg"
)

# Create imported target openenclave::openssl
add_library(openenclave::openssl INTERFACE IMPORTED)

set_target_properties(openenclave::openssl PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::opensslcrypto;openenclave::opensslssl"
)

# Create imported target openenclave::openssl-lvi-cfg
add_library(openenclave::openssl-lvi-cfg INTERFACE IMPORTED)

set_target_properties(openenclave::openssl-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::opensslcrypto-lvi-cfg;openenclave::opensslssl-lvi-cfg"
)

# Create imported target openenclave::oelibc
add_library(openenclave::oelibc STATIC IMPORTED)

set_target_properties(openenclave::oelibc PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oesyscall;openenclave::oecore;openenclave::oelibc_includes;\$<LINK_ONLY:openenclave::oelibasm>"
)

# Create imported target openenclave::oelibc-lvi-cfg
add_library(openenclave::oelibc-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oelibc-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oesyscall-lvi-cfg;openenclave::oecore-lvi-cfg;openenclave::oelibc_includes;\$<LINK_ONLY:openenclave::oelibasm-lvi-cfg>"
)

# Create imported target openenclave::oelibasm
add_library(openenclave::oelibasm INTERFACE IMPORTED)

# Create imported target openenclave::oelibasm-lvi-cfg
add_library(openenclave::oelibasm-lvi-cfg INTERFACE IMPORTED)

# Create imported target openenclave::oelibcxx
add_library(openenclave::oelibcxx STATIC IMPORTED)

set_target_properties(openenclave::oelibcxx PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::libcxx;openenclave::libcxxrt;openenclave::libunwind"
)

# Create imported target openenclave::oelibcxx-lvi-cfg
add_library(openenclave::oelibcxx-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oelibcxx-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::libcxx-lvi-cfg;openenclave::libcxxrt-lvi-cfg;openenclave::libunwind-lvi-cfg"
)

# Create imported target openenclave::oesyscall
add_library(openenclave::oesyscall STATIC IMPORTED)

set_target_properties(openenclave::oesyscall PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oelibc_includes>;openenclave::oecore"
)

# Create imported target openenclave::oesyscall-lvi-cfg
add_library(openenclave::oesyscall-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oesyscall-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oelibc_includes>;openenclave::oecore-lvi-cfg"
)

# Create imported target openenclave::oehostfs
add_library(openenclave::oehostfs STATIC IMPORTED)

set_target_properties(openenclave::oehostfs PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall>"
)

# Create imported target openenclave::oehostfs-lvi-cfg
add_library(openenclave::oehostfs-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oehostfs-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall-lvi-cfg>"
)

# Create imported target openenclave::oehostresolver
add_library(openenclave::oehostresolver STATIC IMPORTED)

set_target_properties(openenclave::oehostresolver PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall>"
)

# Create imported target openenclave::oehostresolver-lvi-cfg
add_library(openenclave::oehostresolver-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oehostresolver-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall-lvi-cfg>"
)

# Create imported target openenclave::oehostsock
add_library(openenclave::oehostsock STATIC IMPORTED)

set_target_properties(openenclave::oehostsock PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall>"
)

# Create imported target openenclave::oehostsock-lvi-cfg
add_library(openenclave::oehostsock-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oehostsock-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall-lvi-cfg>"
)

# Create imported target openenclave::oehostepoll
add_library(openenclave::oehostepoll STATIC IMPORTED)

set_target_properties(openenclave::oehostepoll PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall>"
)

# Create imported target openenclave::oehostepoll-lvi-cfg
add_library(openenclave::oehostepoll-lvi-cfg STATIC IMPORTED)

set_target_properties(openenclave::oehostepoll-lvi-cfg PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall-lvi-cfg>"
)

# Create imported target openenclave::oedebugrt
add_library(openenclave::oedebugrt INTERFACE IMPORTED)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/openenclave-targets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
