# Generated by CMake

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget openenclave::oe_includes openenclave::oehost openenclave::oecore openenclave::oedebugmalloc openenclave::oecryptombedtls openenclave::oeenclave openenclave::oedlmalloc_obj openenclave::libcxx openenclave::libcxxrt openenclave::libunwind openenclave::oelibc_includes openenclave::mbedcrypto_static openenclave::mbedx509 openenclave::mbedtls openenclave::mbedcrypto openenclave::oelibutee openenclave::oelibutee_includes openenclave::oeutee openenclave::oeuteeasm openenclave::teec openenclave::oelibc openenclave::oelibasm openenclave::oelibcxx openenclave::oesyscall openenclave::oehostfs openenclave::oehostresolver openenclave::oehostsock openenclave::oehostepoll)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Compute the installation prefix relative to this file.
get_filename_component(_IMPORT_PREFIX "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
get_filename_component(_IMPORT_PREFIX "${_IMPORT_PREFIX}" PATH)
if(_IMPORT_PREFIX STREQUAL "/")
  set(_IMPORT_PREFIX "")
endif()

# Create imported target openenclave::oe_includes
add_library(openenclave::oe_includes INTERFACE IMPORTED)

set_target_properties(openenclave::oe_includes PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
)

# Create imported target openenclave::oehost
add_library(openenclave::oehost STATIC IMPORTED)

set_target_properties(openenclave::oehost PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "\$<\$<NOT:\$<CONFIG:debug>>:_FORTIFY_SOURCE=2>"
  INTERFACE_COMPILE_OPTIONS "-fstack-protector-strong"
  INTERFACE_LINK_LIBRARIES "openenclave::oe_includes;\$<LINK_ONLY:openenclave::crypto>;\$<LINK_ONLY:openenclave::dl>;\$<LINK_ONLY:Threads::Threads>;\$<LINK_ONLY:openenclave::teec>;-Wl,-z,noexecstack"
)

# Create imported target openenclave::oecore
add_library(openenclave::oecore STATIC IMPORTED)

set_target_properties(openenclave::oecore PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "OE_BUILD_ENCLAVE"
  INTERFACE_COMPILE_OPTIONS "-fvisibility=hidden;-DARM64=1;-D__LP64__=1;-mstrict-align;-nostdinc;-nostdlib;-nodefaultlibs;-nostartfiles;-fno-builtin-memcpy;-fno-builtin-memset;-ffreestanding;-funwind-tables;-fpie;-fPIC;-gdwarf;\$<\$<COMPILE_LANGUAGE:CXX>:-nostdinc++>"
  INTERFACE_LINK_LIBRARIES "openenclave::oe_includes;openenclave::oelibutee_includes;openenclave::oe_includes;openenclave::oedlmalloc_obj;-nostdlib;-nodefaultlibs;-nostartfiles;--no-undefined;-pie;--sort-section=alignment;-z max-page-size=4096;--as-needed"
)

# Create imported target openenclave::oedebugmalloc
add_library(openenclave::oedebugmalloc STATIC IMPORTED)

set_target_properties(openenclave::oedebugmalloc PROPERTIES
  INTERFACE_COMPILE_DEFINITIONS "OE_USE_DEBUG_MALLOC"
  INTERFACE_LINK_LIBRARIES "openenclave::oecore"
)

# Create imported target openenclave::oecryptombedtls
add_library(openenclave::oecryptombedtls STATIC IMPORTED)

set_target_properties(openenclave::oecryptombedtls PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedcrypto"
)

# Create imported target openenclave::oeenclave
add_library(openenclave::oeenclave STATIC IMPORTED)

set_target_properties(openenclave::oeenclave PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-DARM64=1;-D__LP64__=1;-mstrict-align;-nostdinc;-nostdlib;-nodefaultlibs;-nostartfiles;-fno-builtin-memcpy;-fno-builtin-memset;-ffreestanding;-funwind-tables;-fpie;-fPIC;-gdwarf"
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc;openenclave::oelibutee"
)

# Create imported target openenclave::oedlmalloc_obj
add_library(openenclave::oedlmalloc_obj INTERFACE IMPORTED)

set_target_properties(openenclave::oedlmalloc_obj PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibutee_includes"
)

# Create imported target openenclave::libcxx
add_library(openenclave::libcxx INTERFACE IMPORTED)

set_target_properties(openenclave::libcxx PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc"
)

# Create imported target openenclave::libcxxrt
add_library(openenclave::libcxxrt INTERFACE IMPORTED)

set_target_properties(openenclave::libcxxrt PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc"
)

# Create imported target openenclave::libunwind
add_library(openenclave::libunwind INTERFACE IMPORTED)

set_target_properties(openenclave::libunwind PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc"
)

# Create imported target openenclave::oelibc_includes
add_library(openenclave::oelibc_includes INTERFACE IMPORTED)

set_target_properties(openenclave::oelibc_includes PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-Wno-implicit-fallthrough"
  INTERFACE_INCLUDE_DIRECTORIES "\$<\$<COMPILE_LANGUAGE:CXX>:${_IMPORT_PREFIX}/include/openenclave/3rdparty/libcxx>;${_IMPORT_PREFIX}/include/openenclave/3rdparty/libc"
)

# Create imported target openenclave::mbedcrypto_static
add_library(openenclave::mbedcrypto_static STATIC IMPORTED)

set_target_properties(openenclave::mbedcrypto_static PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/openenclave/3rdparty"
  INTERFACE_LINK_LIBRARIES "openenclave::oelibc;openenclave::oe_includes"
)

# Create imported target openenclave::mbedx509
add_library(openenclave::mbedx509 STATIC IMPORTED)

set_target_properties(openenclave::mbedx509 PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedcrypto_static"
)

# Create imported target openenclave::mbedtls
add_library(openenclave::mbedtls STATIC IMPORTED)

set_target_properties(openenclave::mbedtls PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedx509"
)

# Create imported target openenclave::mbedcrypto
add_library(openenclave::mbedcrypto INTERFACE IMPORTED)

set_target_properties(openenclave::mbedcrypto PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::mbedtls"
)

# Create imported target openenclave::oelibutee
add_library(openenclave::oelibutee INTERFACE IMPORTED)

set_target_properties(openenclave::oelibutee PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oeutee;openenclave::oelibutee_includes;--undefined=TEE_GenerateRandom"
)

# Create imported target openenclave::oelibutee_includes
add_library(openenclave::oelibutee_includes INTERFACE IMPORTED)

set_target_properties(openenclave::oelibutee_includes PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include/openenclave/3rdparty/optee/liboeutee"
)

# Create imported target openenclave::oeutee
add_library(openenclave::oeutee STATIC IMPORTED)

set_target_properties(openenclave::oeutee PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-include;openenclave/3rdparty/optee/conf.h"
  INTERFACE_LINK_LIBRARIES "openenclave::oeuteeasm;openenclave::oelibc"
)

# Create imported target openenclave::oeuteeasm
add_library(openenclave::oeuteeasm STATIC IMPORTED)

# Create imported target openenclave::teec
add_library(openenclave::teec INTERFACE IMPORTED)

set_target_properties(openenclave::teec PROPERTIES
  INTERFACE_LINK_LIBRARIES "${_IMPORT_PREFIX}/lib/openenclave/optee/libteec/libteec.a"
)

# Create imported target openenclave::oelibc
add_library(openenclave::oelibc STATIC IMPORTED)

set_target_properties(openenclave::oelibc PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::oesyscall;openenclave::oecore;openenclave::oelibc_includes;\$<LINK_ONLY:openenclave::oelibasm>"
)

# Create imported target openenclave::oelibasm
add_library(openenclave::oelibasm INTERFACE IMPORTED)

# Create imported target openenclave::oelibcxx
add_library(openenclave::oelibcxx STATIC IMPORTED)

set_target_properties(openenclave::oelibcxx PROPERTIES
  INTERFACE_LINK_LIBRARIES "openenclave::libcxx;openenclave::libcxxrt;openenclave::libunwind"
)

# Create imported target openenclave::oesyscall
add_library(openenclave::oesyscall STATIC IMPORTED)

set_target_properties(openenclave::oesyscall PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oelibc_includes>;openenclave::oecore"
)

# Create imported target openenclave::oehostfs
add_library(openenclave::oehostfs STATIC IMPORTED)

set_target_properties(openenclave::oehostfs PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall>"
)

# Create imported target openenclave::oehostresolver
add_library(openenclave::oehostresolver STATIC IMPORTED)

set_target_properties(openenclave::oehostresolver PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall>"
)

# Create imported target openenclave::oehostsock
add_library(openenclave::oehostsock STATIC IMPORTED)

set_target_properties(openenclave::oehostsock PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall>"
)

# Create imported target openenclave::oehostepoll
add_library(openenclave::oehostepoll STATIC IMPORTED)

set_target_properties(openenclave::oehostepoll PROPERTIES
  INTERFACE_LINK_LIBRARIES "\$<LINK_ONLY:openenclave::oesyscall>"
)

if(CMAKE_VERSION VERSION_LESS 3.0.0)
  message(FATAL_ERROR "This file relies on consumers using CMake 3.0.0 or greater.")
endif()

# Load information for each installed configuration.
get_filename_component(_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
file(GLOB CONFIG_FILES "${_DIR}/openenclave-targets-*.cmake")
foreach(f ${CONFIG_FILES})
  include(${f})
endforeach()

# Cleanup temporary variables.
set(_IMPORT_PREFIX)

# Loop over all imported files and verify that they actually exist
foreach(target ${_IMPORT_CHECK_TARGETS} )
  foreach(file ${_IMPORT_CHECK_FILES_FOR_${target}} )
    if(NOT EXISTS "${file}" )
      message(FATAL_ERROR "The imported target \"${target}\" references the file
   \"${file}\"
but this file does not exist.  Possible reasons include:
* The file was deleted, renamed, or moved to another location.
* An install or uninstall procedure did not complete successfully.
* The installation package was faulty and contained
   \"${CMAKE_CURRENT_LIST_FILE}\"
but not all the files it references.
")
    endif()
  endforeach()
  unset(_IMPORT_CHECK_FILES_FOR_${target})
endforeach()
unset(_IMPORT_CHECK_TARGETS)

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
